# Generated by Django 4.1.3 on 2022-12-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("traits", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(
                default=None, related_name="Pets", to="traits.trait"
            ),
        ),
    ]
