# Generated by Django 4.1.3 on 2022-12-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="pets",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Groups",
                to="pets.pet",
            ),
        ),
    ]
